name: 'PROJECT_CUST_SUBS'
version: '1.0.0'
config-version: 2

profile: 'customer_subscription_project'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  customer_subscription_project:
    +schema: public
    +materialized: view
